version: '3.8'

networks:
  minha-rede:
    driver: bridge

services:
  httpd:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    -  '80:80'
    restart: always
    volumes:
      - ./website:/usr/local/apache2/htdocs
    networks:
      - minha-rede
